on:
  workflow_run:
    workflows: ["Frontend CI"]
    branches: ["main"]
    types:
      - completed

name: Deploy Frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      — uses: actions/checkout@v2
      — name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
      - name: Build
        run: yarn && cd frontend/ && yarn && yarn build

      - name: Deploy to Skynet
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: frontend/build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.REGISTRY_SEED || '' }}
          registry-datakey: ${{ secrets.REGISTRY_DATAKEY || '' }}
